//! Generate a sample report document.
//!
//! Usage: cargo run --example create_report
//!
//! Demonstrates:
//! - DocumentBuilder API
//! - Headings, paragraphs, tables
//! - Inline formatting (bold, italic, underline)
//! - Metadata
//! - Exporting to multiple formats

use s1engine::{DocumentBuilder, Format};

fn main() {
    let doc = DocumentBuilder::new()
        .title("Q4 2026 Report")
        .author("Engineering Team")
        .heading(1, "Quarterly Report")
        .paragraph(|p| {
            p.text("Revenue grew by ")
                .bold("23%")
                .text(" compared to Q3. Customer satisfaction remained ")
                .italic("above target")
                .text(" across all segments.")
        })
        .heading(2, "Key Metrics")
        .table(|t| {
            t.row(|r| r.cell("Metric").cell("Q3").cell("Q4").cell("Change"))
                .row(|r| {
                    r.cell("Active Users")
                        .cell("10,000")
                        .cell("15,000")
                        .cell("+50%")
                })
                .row(|r| {
                    r.cell("Revenue")
                        .cell("$1.2M")
                        .cell("$1.5M")
                        .cell("+25%")
                })
                .row(|r| r.cell("NPS").cell("72").cell("78").cell("+6"))
        })
        .heading(2, "Highlights")
        .bullet("Launched v2.0 platform redesign")
        .bullet("Expanded to 3 new markets")
        .bullet("Reduced infrastructure costs by 15%")
        .heading(2, "Next Steps")
        .numbered("Finalize Q1 roadmap")
        .numbered("Hire 5 additional engineers")
        .numbered("Launch mobile app beta")
        .paragraph(|p| p.text("Report generated by s1engine."))
        .build();

    // Print document info
    println!("Title: {:?}", doc.metadata().title);
    println!("Author: {:?}", doc.metadata().creator);
    println!("Paragraphs: {}", doc.paragraph_count());
    println!("Plain text preview:");
    let text = doc.to_plain_text();
    for line in text.lines().take(10) {
        println!("  {line}");
    }
    if text.lines().count() > 10 {
        println!("  ...");
    }
    println!();

    // Export to DOCX
    let docx = doc.export(Format::Docx).unwrap();
    std::fs::write("report.docx", &docx).unwrap();
    println!("Wrote report.docx ({} bytes)", docx.len());

    // Export to ODT
    let odt = doc.export(Format::Odt).unwrap();
    std::fs::write("report.odt", &odt).unwrap();
    println!("Wrote report.odt ({} bytes)", odt.len());

    // Export to TXT
    let txt = doc.export(Format::Txt).unwrap();
    std::fs::write("report.txt", &txt).unwrap();
    println!("Wrote report.txt ({} bytes)", txt.len());
}
